version: '3'

networks:
  lumen:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres
    networks:
      - lumen

  postgres:
    image: postgres:11.8-alpine
    container_name: postgres
    restart: unless-stopped
    tty: true
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/var/lib/postgres
    environment:
      POSTGRES_PASSWORD: secret
    networks:
      - lumen

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - '9000:9000'
    networks:
      - lumen

  composer:
    image: composer:latest
    container_name: composer
    depends_on:
      - php
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - lumen

  npm:
    image: node:lts-stretch-slim
    container_name: npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - lumen